config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root 'dashboard#index', as: :dashboard
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get '/agents' => 'agents#index', as: :agents
  get '/agents/new' => 'agents#new', as: :new_agent
  get '/agents/:id' => 'agents#show', as: :agent
  get '/agents/:id/edit' => 'agents#edit', as: :edit_agent
  post '/agents' => 'agents#create'
  patch '/agents/:id' => 'agents#update'
  delete '/agents/:id' => 'agents#destroy'

  get '/listings/search' => 'search#listings_search', as: :listings_search
  get '/listings/:id' => 'listings#show', as: :listing

  resources :appointments

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  # attr_accessor :board_name
  has_many :agents_listings
  has_many :agents, through: :agents_listings

  def self.default_select
    "listings.*, (SELECT boards.name FROM boards WHERE boards.id=listings.board_id) AS board_name, IFNULL(agents_listings.read, 0) AS _read"
  end

  def mark_read user
    sql = "
      SELECT agents_listings.* FROM users
      INNER JOIN agents ON users.id = agents.user_id
      INNER JOIN agents_listings ON agents_listings.agent_id = agents.id AND agents_listings.listing_id=#{id}
      WHERE users.id=#{user.id}
      LIMIT 1
    "

    result = ActiveRecord::Base.connection.exec_query(sql).first
    result.if true: ->{
      agents_listing = AgentsListing.find(result["id"])
      agents_listing.update read: true
    }, false: ->{
      false
    }
  end

  def read?
    {true => true, false => false, 0 => false, 1 => true}[_read]
  rescue
    false
  end

  def read_class
    read?.if true: ->{"read"}, false: ->{"unread"}
  end

  private
  def self.create_unless_exists params
    where(remote_id: params[:remote_id], agent_id: params[:agent_id]).first_or_create(params)
  end
end

app/controllers/listings_controller.rb
class ListingsController < UserApplicationController
  def show
    @listing = @user.listings.select(Listing.default_select).find(params[:id]) 
    @listing.mark_read @user
  end
end

app/views/listings/_result.html.slim
.panel.panel-default.listings-result class=listing.read_class
  .panel-body
    .col-md-12
      h3 = link_to listing.title, listing_path(listing)
      h4 = link_to listing.board_name, listing.url, target: "_blank"
      div
        span.badge  #{time_ago_in_words(listing.posted_at)} ago
      p = raw listing.description.truncate(250)
      div
        / span.badge = listing.posted_at
        .pull-right
          / span.label.label-default alice
          / span.label.label-primary story
          / span.label.label-success blog
          / span.label.label-info personal
          / span.label.label-warning Warning
          / span.label.label-danger Danger
      hr/

app/views/listings/search.html.slim
h3 Search results for your query

- @listings.each do |listing|
  = render partial: "listings/result", locals: {listing: listing}

app/views/listings/show.html.slim
.panel.panel-default
  .panel-body
    .col-md-12
      h3 = link_to @listing.title, @listing.url, target: "_blank"
      h4 = link_to @listing.board_name, @listing.url, target: "_blank"
      div
        span.badge = @listing.posted_at
      p = raw @listing.description
      div
        / span.badge = listing.posted_at
        .pull-right
          / span.label.label-default alice
          / span.label.label-primary story
          / span.label.label-success blog
          / span.label.label-info personal
          / span.label.label-warning Warning
          / span.label.label-danger Danger
      hr/