config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root 'dashboard#index', as: :dashboard
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get '/agents' => 'agents#index', as: :agents
  get '/agents/new' => 'agents#new', as: :new_agent
  get '/agents/:id' => 'agents#show', as: :agent
  get '/agents/:id/edit' => 'agents#edit', as: :edit_agent
  post '/agents' => 'agents#create'
  patch '/agents/:id' => 'agents#update'
  delete '/agents/:id' => 'agents#destroy'

  get '/listings/search' => 'search#listings_search', as: :listings_search
  get '/listings/:id' => 'listings#show', as: :listing

  resources :appointments

end

app/models/agent.rb
class Agent < RexModel
  has_many :agents_listings
  has_many :listings, through: :agents_listings
  belongs_to :location
  belongs_to :user
  before_create :assign_name
  validates :terms, presence: true

  # include RexModel
  attr_accessor :location_name, :jobs_found

  def find_new_listings scraper_class
    scraper = scraper_class.new self
    scraper.download
    scraper.write
  end
  def notify listing
    # ListingsMailer.notify("benjamin@pixelstreetinc.com", listing).deliver_now
  end
  def activeness
    {true => "Active", false => "Inactive"}[active]
  end
  private
  def assign_name
    self.name = AGENT_NAMES.sample
  end
end

app/controllers/agents_controller.rb
class AgentsController < UserApplicationController
  def index
    @agents = @user.agents_with_extra_data
  end
  def new
    @agent = Agent.new
  end
  def create
    @agent = Agent.new agent_params
    @user.accepts_new_agents?.if true: ->{ create_new_agent }, false: ->{ cant_create }
  end
  def show
    @agent = @user.agents.find(params[:id])
    @listings = @agent.listings.select(Listing.default_select)
  end
  def edit
    @agent = @user.agents.find(params[:id])
  end
  def update
    @agent = @user.agents.find(params[:id])
    @agent.update(agent_params).if true: ->{
      redirect_to agents_path
    },
    false: ->{
      render :edit
    }
  end
  def destroy
    @agent = @user.agents.find(params[:id])
    @agent.delete
    redirect_to agents_path
  end
  private
  def create_new_agent
    @agent = @user.agents.create agent_params
    @agent.saved?.if true: ->{
      redirect_to agents_path
    },
    false: ->{
      cant_create
    }
  end
  def cant_create
    render :new    
  end
  def agent_params
    params.require(:agent).permit(:terms, :location_id, :auto_send_resume, :email_updates, :whitelist, :blacklist)
  end
end

app/views/agents/_form.html.slim
= form_for agent do |f|
  label Terms
  = f.text_field :terms
  label Location
  = f.collection_select :location_id, Location.all , :id, :city, include_blank: false
  label Whitelist
  = f.text_field :whitelist
  label Blacklist
  = f.text_field :blacklist
  label Email Updates
  = f.check_box :email_updates
  = f.submit

app/views/agents/edit.html.slim
h2 Edit

= render partial: "form", locals: {agent: @agent}

app/views/agents/index.html.slim
h2 Agents

= link_to "New Agent", new_agent_path, class: "btn btn-success"

table.table.table-striped
  thead
    th Name
    th Terms
    th Location
    th Jobs Found
    th Whitelist
    th Blacklist
    th Active?
    th
  tbody
    - @agents.each do |agent|
      tr
        td = link_to "Agent #{agent.name}", agent_path(agent)
        td = agent.terms.truncate(10)
        td = agent.location_name
        td = agent.jobs_found
        td = agent.whitelist.truncate(10)
        td = agent.blacklist.truncate(10)
        td = agent.active
        td
          = link_to "Edit", edit_agent_path(agent), class: "btn btn-warning btn-xs"
          = link_to "Delete", agent_path(agent), class: "btn btn-danger btn-xs", method: :delete

app/views/agents/new.html.slim
h2 New Agent

= render partial: "form", locals: {agent: @agent}

app/views/agents/show.html.slim
h2 Agent #{@agent.name}

- @listings.each do |listing|
  = render partial: "listings/result", locals: {listing: listing}