config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root 'dashboard#index', as: :dashboard
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get '/agents' => 'agents#index', as: :agents
  get '/agents/new' => 'agents#new', as: :new_agent
  get '/agents/:id' => 'agents#show', as: :agent
  get '/agents/:id/edit' => 'agents#edit', as: :edit_agent
  post '/agents' => 'agents#create'
  patch '/agents/:id' => 'agents#update'
  delete '/agents/:id' => 'agents#destroy'

  get '/listings/search' => 'search#listings_search', as: :listings_search
  get '/listings/:id' => 'listings#show', as: :listing

  resources :appointments

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  def in_words
    "#{name} with #{person} from #{company} at #{time}"
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < UserApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = @user.appointments.new appointment_params

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_appointment
      @appointment = @user.appointments.find(params[:id])
    end

    def appointment_params
      params.require(:appointment).permit(:name, :person, :company, :description, :time)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.slim
= form_for @appointment do |f|
  - if @appointment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@appointment.errors.count, "error")} prohibited this appointment from being saved:"
      ul
        - @appointment.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field
    = f.label :person
    = f.text_field :person
  .field
    = f.label :company
    = f.text_field :company
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :time
    = f.datetime_select :time
  .field
    = f.label :user
    = f.text_field :user
  .actions = f.submit

app/views/appointments/edit.html.slim
h1 Editing appointment

== render 'form'

= link_to 'Show', @appointment
'|
= link_to 'Back', appointments_path

app/views/appointments/index.html.slim
h1 Listing appointments
= link_to 'New Appointment', new_appointment_path, class: "btn btn-success"

table.table.table-striped
  thead
    tr
      / th Name
      / th Person
      / th Company
      / th Description
      / th Time
      / th User
      th
      th
      th
      th

  tbody
    - @appointments.each do |appointment|
      tr
        td 
          = link_to appointment_path(appointment) do 
            = appointment.in_words
          = time_ago_in_words appointment.time
        / td = appointment.name
        / td = appointment.person
        / td = appointment.company
        / td = appointment.description
        / td = appointment.time
        / td = appointment.user
        td = link_to 'Edit', edit_appointment_path(appointment), class: "btn btn-warning btn-xs"
        td = link_to 'Delete', appointment, data: {:confirm => 'Are you sure?'}, :method => :delete, class: "btn btn-danger btn-xs"

br

app/views/appointments/new.html.slim
h1 New appointment

== render 'form'

= link_to 'Back', appointments_path

app/views/appointments/show.html.slim
p#notice = notice

p
  strong Name:
  = @appointment.name
p
  strong Person:
  = @appointment.person
p
  strong Company:
  = @appointment.company
p
  strong Description:
  = @appointment.description
p
  strong Time:
  = @appointment.time
p
  strong User:
  = @appointment.user

= link_to 'Edit', edit_appointment_path(@appointment)
'|
= link_to 'Back', appointments_path