config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root 'dashboard#index', as: :dashboard
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get '/agents' => 'agents#index', as: :agents
  get '/agents/new' => 'agents#new', as: :new_agent
  get '/agents/:id' => 'agents#show', as: :agent
  get '/agents/:id/edit' => 'agents#edit', as: :edit_agent
  post '/agents' => 'agents#create'
  patch '/agents/:id' => 'agents#update'
  delete '/agents/:id' => 'agents#destroy'

  get '/listings/search' => 'search#listings_search', as: :listings_search
  get '/listings/:id' => 'listings#show', as: :listing

  resources :appointments

end

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Agent Rex", dashboard_path, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          = link_to agents_path do
            | Agents
            span.sr-only (current)
        li
          = link_to "Appointments", appointments_path
      = form_tag listings_search_path, action: "listings/search", method: :get, class: "navbar-form navbar-left" do
        .form-group
          = text_field_tag :query, listing_search, placeholder: "Search Jobs", class: "form-control"
          = submit_tag "Search", class: "btn btn-default"
          / input.form-control placeholder="Search" type="text" /
        / button.btn.btn-default type="submit"  Submit
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "Sign out", destroy_user_session_path, method: :delete
        li.dropdown
          a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#" role="button" 
            = @user.full_name
            span.caret
          ul.dropdown-menu role="menu" 
            li
              a href="#"  Action
            li
              a href="#"  Another action
            li
              a href="#"  Something else here
            li.divider
            li
              a href="#"  Separated link

app/views/layouts/application.html.slim
doctype html
html
  head
    title Agent Rex
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield

app/views/layouts/user.html.slim
doctype html
html
  head
    title Agent Rex
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render partial: "layouts/navbar", locals: {listing_search: @listing_search}
    = yield